theme: minima
title: Mitch's Blog
author: mitch-ml
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog, check it out!

# social links
twitter_username: mitch-ml # DO NOT include the @ character, or else the build will fail!
github_username:  mitch-ml # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
